#!/bin/sh

# uses usbipd to search for USB port that vbuddy is connected to and share with WSL.
 ~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace f1_sim.sv --exe f1_sim_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_sim.mk Vf1_sim

# run executable simulation file
obj_dir/Vf1_sim